name: deploy
on: push
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-suggest

      - name: Transfer files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: va1b3.ftp.infomaniak.com
          username: va1b3_salmina
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
